# Generated by Django 5.2.8 on 2026-03-12 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at", "status"], name="orders_orde_created_4a9c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["paid_at"], name="orders_orde_paid_at_8fa0ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["new_status", "-created_at"],
                name="orders_orde_new_sta_aa82c2_idx",
            ),
        ),
    ]
