# Generated by Django 5.2.8 on 2026-03-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_orders_orde_created_4a9c8f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Pickup address (snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_city",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Pickup city (snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_location_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Pickup location name (snapshot)",
            ),
        ),
        migrations.CreateModel(
            name="PickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=120, verbose_name="City")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Pickup point name"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address line 2"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Phone"),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Working hours"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pickup location",
                "verbose_name_plural": "Pickup locations",
                "ordering": ["sort_order", "city", "name"],
                "indexes": [
                    models.Index(
                        fields=["city", "is_active"], name="orders_pick_city_c6e0cf_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.pickuplocation",
                verbose_name="Pickup location",
            ),
        ),
    ]
