# Generated by Django 5.2.8 on 2026-03-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_pickup_address_order_pickup_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address line 1"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="City"),
        ),
    ]
