# Generated by Django 5.2.8 on 2026-03-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_coupon_arrivalwindow_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_variant",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
