# Generated by Django 5.1.2 on 2026-02-26 02:49

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('color', 'Color')], max_length=20)),
                ('is_multiple', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name': 'fashion accessory', 'verbose_name_plural': 'fashion accessories'},
        ),
        migrations.AlterModelOptions(
            name='beauty',
            options={'verbose_name': 'beauty or health product', 'verbose_name_plural': 'beauty and health products'},
        ),
        migrations.AlterModelOptions(
            name='electronics',
            options={'verbose_name': 'electronic device or gadget', 'verbose_name_plural': 'electronic devices and gadgets'},
        ),
        migrations.AlterModelOptions(
            name='homeproduct',
            options={'verbose_name': 'home and interior product', 'verbose_name_plural': 'home and interior products'},
        ),
        migrations.AlterModelOptions(
            name='kidsclothes',
            options={'verbose_name': "children's clothing item", 'verbose_name_plural': "children's clothing"},
        ),
        migrations.AlterModelOptions(
            name='menclothes',
            options={'verbose_name': "men's clothing item", 'verbose_name_plural': "men's clothing"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'pair of shoes', 'verbose_name_plural': 'shoes'},
        ),
        migrations.AlterModelOptions(
            name='sportsproduct',
            options={'verbose_name': 'sports and outdoor product', 'verbose_name_plural': 'sports and outdoor products'},
        ),
        migrations.AlterModelOptions(
            name='womenclothes',
            options={'verbose_name': "women's clothing item", 'verbose_name_plural': "women's clothing"},
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='products.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeIntValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(db_index=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='int', to='products.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeFloatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(db_index=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float', to='products.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeColorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=7)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='products.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeBooleanValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(db_index=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boolean', to='products.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_attributes', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantMultiAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_attributes', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.attribute')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'name'], name='products_at_languag_cf4ded_idx')],
                'unique_together': {('attribute', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AttributeValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.attributevalue')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'name'], name='products_at_languag_86e7e4_idx')],
                'unique_together': {('value', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BrandTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.brand')),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'name'], name='products_br_languag_771353_idx')],
                'unique_together': {('brand', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='products_category_tree_id_0983'),
        ),
        migrations.AddIndex(
            model_name='categorytranslation',
            index=models.Index(fields=['language', 'name'], name='products_ca_languag_9cd0d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together={('category', 'language')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='producttranslation',
            index=models.Index(fields=['language', 'name'], name='products_pr_languag_0532cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('product', 'language')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='products_pr_price_a59bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock'], name='products_pr_stock_c72f45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattribute',
            unique_together={('variant', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='productvariantmultiattribute',
            index=models.Index(fields=['variant', 'attribute'], name='products_pr_variant_ce031a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantmultiattribute',
            unique_together={('variant', 'attribute', 'value')},
        ),
    ]
