# Generated by Django 5.1.2 on 2026-02-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_brand_alter_accessories_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Beauty',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
        migrations.DeleteModel(
            name='HomeProduct',
        ),
        migrations.DeleteModel(
            name='KidsClothes',
        ),
        migrations.DeleteModel(
            name='MenClothes',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.DeleteModel(
            name='SportsProduct',
        ),
        migrations.DeleteModel(
            name='WomenClothes',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
