# Generated by Django 4.2.29 on 2026-03-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_accessories_delete_beauty_delete_electronics_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.AlterField(
            model_name='attributecolorvalue',
            name='value',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'brand'], name='products_pr_is_acti_9e683f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['min_price'], name='products_pr_min_pri_3029f2_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='products_pr_product_cee51f_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantattribute',
            index=models.Index(fields=['variant', 'attribute'], name='products_pr_variant_377fa0_idx'),
        ),
    ]
